name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ main ]

jobs:
  PullRequest:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source de main
      uses: actions/checkout@v4

    - name: Configuration de java 21 corretto
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Construction avec Maven
      run: mvn -B package
