name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ main ]

jobs:
  PullRequest:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source de main
      uses: actions/checkout@v4

    - name: Configuration de java 21 corretto
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Cache des dépendances Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Construction avec Maven
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
